services:
  db:
    platform: linux/amd64
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - teqnet
    volumes:
      - teqgo-db:/var/lib/postgresql
volumes:
  teqgo-db:

networks:
  teqnet: