services:
  db:
    platform: linux/amd64
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - teqnet
    volumes:
      - teqgo-db:/var/lib/postgresql
  mongo-db:
    image: mongo:5.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASS}
    ports:
        - "${DB_MONGO_PORT}:27017"
    networks:
      - teqnet
    volumes:
      - mongodb_data:/data/db
volumes:
  teqgo-db:
  mongodb_data:

networks:
  teqnet: