// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"
	interfaces "go-clean-template/usecase/interfaces"

	mock "github.com/stretchr/testify/mock"
)

// IDBTransaction is an autogenerated mock type for the IDBTransaction type
type IDBTransaction struct {
	mock.Mock
}

type IDBTransaction_Expecter struct {
	mock *mock.Mock
}

func (_m *IDBTransaction) EXPECT() *IDBTransaction_Expecter {
	return &IDBTransaction_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: ctx
func (_m *IDBTransaction) Begin(ctx context.Context) (interfaces.IDBTransaction, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 interfaces.IDBTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (interfaces.IDBTransaction, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) interfaces.IDBTransaction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.IDBTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IDBTransaction_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type IDBTransaction_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IDBTransaction_Expecter) Begin(ctx interface{}) *IDBTransaction_Begin_Call {
	return &IDBTransaction_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *IDBTransaction_Begin_Call) Run(run func(ctx context.Context)) *IDBTransaction_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IDBTransaction_Begin_Call) Return(_a0 interfaces.IDBTransaction, _a1 error) *IDBTransaction_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IDBTransaction_Begin_Call) RunAndReturn(run func(context.Context) (interfaces.IDBTransaction, error)) *IDBTransaction_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function with given fields: ctx
func (_m *IDBTransaction) Commit(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IDBTransaction_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type IDBTransaction_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IDBTransaction_Expecter) Commit(ctx interface{}) *IDBTransaction_Commit_Call {
	return &IDBTransaction_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *IDBTransaction_Commit_Call) Run(run func(ctx context.Context)) *IDBTransaction_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IDBTransaction_Commit_Call) Return(_a0 error) *IDBTransaction_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IDBTransaction_Commit_Call) RunAndReturn(run func(context.Context) error) *IDBTransaction_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *IDBTransaction) Rollback(ctx context.Context) {
	_m.Called(ctx)
}

// IDBTransaction_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type IDBTransaction_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IDBTransaction_Expecter) Rollback(ctx interface{}) *IDBTransaction_Rollback_Call {
	return &IDBTransaction_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *IDBTransaction_Rollback_Call) Run(run func(ctx context.Context)) *IDBTransaction_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IDBTransaction_Rollback_Call) Return() *IDBTransaction_Rollback_Call {
	_c.Call.Return()
	return _c
}

func (_c *IDBTransaction_Rollback_Call) RunAndReturn(run func(context.Context)) *IDBTransaction_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewIDBTransaction creates a new instance of IDBTransaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDBTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDBTransaction {
	mock := &IDBTransaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
