// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ITransactionUseCase is an autogenerated mock type for the ITransactionUseCase type
type ITransactionUseCase struct {
	mock.Mock
}

type ITransactionUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *ITransactionUseCase) EXPECT() *ITransactionUseCase_Expecter {
	return &ITransactionUseCase_Expecter{mock: &_m.Mock}
}

// Deposit provides a mock function with given fields: ctx, walletID, accountID, amount, currency, note
func (_m *ITransactionUseCase) Deposit(ctx context.Context, walletID string, accountID string, amount float64, currency string, note string) error {
	ret := _m.Called(ctx, walletID, accountID, amount, currency, note)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64, string, string) error); ok {
		r0 = rf(ctx, walletID, accountID, amount, currency, note)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ITransactionUseCase_Deposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deposit'
type ITransactionUseCase_Deposit_Call struct {
	*mock.Call
}

// Deposit is a helper method to define mock.On call
//   - ctx context.Context
//   - walletID string
//   - accountID string
//   - amount float64
//   - currency string
//   - note string
func (_e *ITransactionUseCase_Expecter) Deposit(ctx interface{}, walletID interface{}, accountID interface{}, amount interface{}, currency interface{}, note interface{}) *ITransactionUseCase_Deposit_Call {
	return &ITransactionUseCase_Deposit_Call{Call: _e.mock.On("Deposit", ctx, walletID, accountID, amount, currency, note)}
}

func (_c *ITransactionUseCase_Deposit_Call) Run(run func(ctx context.Context, walletID string, accountID string, amount float64, currency string, note string)) *ITransactionUseCase_Deposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(float64), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *ITransactionUseCase_Deposit_Call) Return(_a0 error) *ITransactionUseCase_Deposit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ITransactionUseCase_Deposit_Call) RunAndReturn(run func(context.Context, string, string, float64, string, string) error) *ITransactionUseCase_Deposit_Call {
	_c.Call.Return(run)
	return _c
}

// NewITransactionUseCase creates a new instance of ITransactionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITransactionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITransactionUseCase {
	mock := &ITransactionUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
